# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08aa15f503e91534b6ec909b6896c38340d2ef9e7ea4766fddf7c709ddcb2687897ae0b6203dffacbe64dd1aff223ed6ceef1c0720fae4c9a2d5ed17bea0ee32

test:
  secret_key_base: e4c9eb8222b3606a7966c5651153a2131b18ea1c966160c5b0e0e0f8ae9c44a92fd8e231c1e2bceff388174c2a1800f046e88599794ecede6260923fe0234fba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
